backend:
  name: github
  repo: adi77/tpv-regionentlebuch.ch

#backend:
#  name: test-repo  

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "tpv-pages"
    label: "Seiten"
    files:
      - file: "content/pages/tpv-products/index.md"
        label: "Angebot"
        name: "tpv-products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tpv-products-page"}
          - {label: Slogan, name: slogan, widget: string}
          - {label: Slogan Untertitel, name: slogan-sub, widget: string}
          - {label: Product Claim, name: product-claim, widget: string}
          - {label: Abgebende Eltern, name: abgebende-eltern, widget: object, 
              fields: [
                {label: Überschrift, name: heading, widget: string}, 
                {label: Untertitel, name: subheading, widget: string}, 
                {label: Spalte links, name: abgebende-eltern-left-columns, widget: list, 
                fields: [
                  {label: Überschrift, name: headline, widget: string}, 
                  {label: Inhalt, name: contents, widget: markdown},
                  {label: Body, name: body, widget: markdown}
                  ]
                },
                {label: Spalte rechts, name: abgebende-eltern-right-columns, widget: list, 
                fields: [
                  {label: Überschrift, name: headline, widget: string}, 
                  {label: Inhalt, name: contents, widget: markdown}
                  ]
                }
              ]
            }
          - {label: Tagesfamilien, name: tagesfamilien, widget: object, 
              fields: [
                {label: Überschrift, name: heading, widget: string}, 
                {label: Untertitel, name: subheading, widget: string}, 
                {label: Spalte links, name: tagesfamilien-left-columns, widget: list, 
                fields: [
                  {label: Überschrift, name: headline, widget: string}, 
                  {label: Inhalt, name: contents, widget: markdown}
                  ]
                },
                {label: Spalte rechts, name: tagesfamilien-right-columns, widget: list, 
                fields: [
                  {label: Überschrift, name: headline, widget: string}, 
                  {label: Inhalt, name: contents, widget: markdown}
                  ]
                }
              ]
            }
